In [295]:
import numpy as np
%precision 3

'%.3f'

# Create arrays

In [296]:
x = np.array([ 10, 9 ,-8, 7, 6  ])
y = np.array([ 1,  4 , 9, 4, 16 ])

# Select entries 

### Position
The array index starts from $0$. There are many ways to slice the arrays

In [297]:
x[0 ]  # first element

10

In [298]:
x[-1]  # last element

6

In [299]:
x[1:3] # from 2nd to 3rd element

array([ 9, -8])

In [300]:
x[ :3] # from first to 3rd element

array([10,  9, -8])

In [301]:
x[2: ] # from 3rd to last element

array([-8,  7,  6])

In [302]:
x[-2:] # Last 2 elements

array([7, 6])

In [303]:
np.concatenate( [ x[:2], x[-2:] ] ) # first 2 and last 2 elements

array([10,  9,  7,  6])

### Logical conditions

In [304]:
# Imposing a condition on x returns a boolean array
x>0

array([ True,  True, False,  True,  True], dtype=bool)

In [305]:
# and a boolean array can be used as a mask to extract the entries of an array (x itself in this case)
x[x>0]

array([10,  9,  7,  6])

In [306]:
# We can also define the mask ourselves, by hand:
mask = np.array([ False, False, True, True, False ])

# and use it on x
x[mask]

array([-8,  7])

In [307]:
# or on y (this is possible because x and y have the same number of elements)
y[mask]

array([9, 4])

In [308]:
# masks can be more complicated
mask = (x<=9) & (x>=6)
x[mask]

array([9, 7, 6])

In [309]:
# and can be based on conditions on both x and y
mask = (x > 2*y) & (y>0) & (x>9)
x[mask]

array([10])

In [310]:
# or on other vectors
z = np.array([1,2,31,34,5])
mask = (z>30) | (z==1)    # '|' stands for 'OR' here
x[mask]

array([10, -8,  7])

# Aggregating Functions
They collapse an array to a number

In [311]:
np.mean(x) # Average of values

4.800

In [312]:
np.std(x) # Standard deviation (or volatility) of values

6.554

In [313]:
np.sum(x) # Sum of values

24

In [314]:
np.size(x) # Number of elements

5

# Vectorial operations
Performed element-wise on one array, returning another array with the results

In [315]:
# square root of entries
np.sqrt(y)

array([ 1.,  2.,  3.,  2.,  4.])

In [316]:
# square of entries
x**2

array([100,  81,  64,  49,  36])

In [317]:
# entries to the power 3
x**3

array([1000,  729, -512,  343,  216])

In [318]:
# absolute values of entries
np.abs(x)

array([10,  9,  8,  7,  6])

In [319]:
# logarithm of entries
np.log(y)

array([ 0.   ,  1.386,  2.197,  1.386,  2.773])

In [320]:
# exponential of entries
np.exp(y)

array([  2.718e+00,   5.460e+01,   8.103e+03,   5.460e+01,   8.886e+06])

In [321]:
# opposite of entries
-x

array([-10,  -9,   8,  -7,  -6])

In [322]:
# inverse of entries
1 / x

array([ 0.1  ,  0.111, -0.125,  0.143,  0.167])

# Binary operations
Performed element-wise on two arrays, returning another array with the results

In [323]:
x + y # sums of entries

array([11, 13,  1, 11, 22])

In [324]:
x - y # differences of entries

array([  9,   5, -17,   3, -10])

In [325]:
x * y # products of entries

array([ 10,  36, -72,  28,  96])

In [328]:
x / y # ratios of entries

array([ 10.   ,   2.25 ,  -0.889,   1.75 ,   0.375])

In [329]:
np.minimum(x, y) # minimum of entries

array([ 1,  4, -8,  4,  6])

In [330]:
np.maximum(x, y) # maximum of entries

array([10,  9,  9,  7, 16])

# Where
'np.where' is conceptually similar to an 'if' and can be used to generate arrays based on given conditions

In [331]:
np.where( x > 0, 1, -1)

array([ 1,  1, -1,  1,  1])

In [332]:
np.where( x > 0, 'Positive', 'Negative')

array(['Positive', 'Positive', 'Negative', 'Positive', 'Positive'], 
      dtype='<U8')

In [333]:
# they can be nested iside each other to achieve more complex logic
np.where( x > 9, 'High', np.where( x > 6, 'Medium', 'Low' ))

array(['High', 'Medium', 'Low', 'Medium', 'Low'], 
      dtype='<U6')

## np.unique()

In [334]:
z = np.array([1,2,3,3,3,5])
np.unique(z) # unique values of the array (removes duplicates)

array([1, 2, 3, 5])

## Itrerables
elements of an array can be iterated over, in a for loop of in a list comprehension

In [335]:
[ 2*a for a in x ] # List comprehension

[20, 18, -16, 14, 12]

In [336]:
[ 2*a for a in x if a > 0 ] # List comprehension with condition

[20, 18, 14, 12]

In [337]:
for a in x:
    print(a, end=' • ')

10 • 9 • -8 • 7 • 6 • 

In [338]:
for i, a in enumerate(x):
    print("We have %d \t on position %d of x"%(a,i))

We have 10 	 on position 0 of x
We have 9 	 on position 1 of x
We have -8 	 on position 2 of x
We have 7 	 on position 3 of x
We have 6 	 on position 4 of x


## Exercise (solved)
Consider an array $r$ with returns over 1 year (in percentage) of different investment opportunities

In [339]:
r = np.array([ 0.05, 0.1, -0.15, 0.2 ])  # 5% profit, 10% profit, 15% loss, ...

### What is the returns of an equally weighted portfolio of all the investments?

In [340]:
# It is just the average of the returns of all the investments
np.mean(r)

0.050

In [341]:
# or, equivalently
np.sum(r) / len(r)

0.050

### What is the return of a portfolio with 40% of capital invested in each of the first 2 investments, and 10% in each of the other ones?

In [342]:
# first we create the 'portfolio weights'
w = np.array([0.4, 0.4, 0.1, 0.1])

In [343]:
# Notice that they sum to 1 (or 100%)
np.sum(w)

1.000

In [344]:
# Then we compute the weighted average to get the total profit of the portfolio
np.sum( w * r )

0.065